ifeval::["{backend}" == "pdf"]
[discrete]
endif::[]
= Copyright
${include("_header.adoc", always_embed=True, leveloffset=None)}

This book is copyright David Chisnall under the CC BY-NC 4.0 license.

Portions of the text and code listings are part of the CHERIoT RTOS project and are licensed under the MIT license:
\amanda{The MIT license wraps strangely, both in the HTML version and the PDF.  I would recommend removing the <pre></pre>tags and making a special class in the stylesheet to use the font.  I am not entirely certain what causes the PDF to wrap and if removing the <pre></pre> tags will fix the PDF as well, but the PDF is fixed-width and there's no good reason for it to have strange line-breaks.  Alternatively, I can go through and re-break all the lines to fit the PDF but that will still leave weird wrapping on the HTML on smaller screens.}

----
MIT License

Copyright (c) Microsoft Corporation and CHERIoT RTOS contributors.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE
----

