= CHERIoT Programmers' Guide
David Chisnall
:source-highlighter: rouge
:toc: macro
:doctype: book
:xrefstyle: short
:icons: font
:toc: right
${include("_header.adoc", always_embed=True, leveloffset=None)}

This is a public draft of the CHERIoT Programmers' Guide.

WARNING: This is an early draft.
It is public for early feedback and to help people get started with the CHERIoT Platform.
It is guaranteed to contain errors, both factual and typographic.

${include("copyright.adoc", multipage_link=False)}

ifeval::["{backend}" == "pdf"]
toc::[]
endif::[]
ifeval::["{backend}" != "pdf"]
This document is also link:cheriot-programmers-guide.pdf[available as a PDF].
endif::[]

:sectnums:

${include("concepts.adoc", multipage_link=False)}
${include("core_rtos.adoc", multipage_link=False)}
${include("language_extensions.adoc", multipage_link=False)}
${include("compartments.adoc", multipage_link=False)}
${include("threads.adoc", multipage_link=False)}

${include("memory.adoc", multipage_link=False)}
${include("debugging_apis.adoc", multipage_link=False)}
${include("drivers.adoc", multipage_link=False)}
${include("porting_from_bare_metal.adoc", multipage_link=False)}
${include("porting_from_freertos.adoc", multipage_link=False)}

